name: Compile LaTeX Files

on:
  push:
    paths:
      - 'input/start.start' # This trigger path is still here, but the job's 'if' will control execution
  pull_request:
    paths:
      - 'input/start.start' # Same here
  workflow_dispatch:

permissions:
  contents: write

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check for inprogress.inprogress file
        id: check_inprogress_file
        run: |
          if [ -f "input/inprogress.inprogress" ]; then
            echo "inprogress_file_exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "inprogress_file_exists=false" >> "$GITHUB_OUTPUT"
          fi
        shell: bash

      - name: Install LaTeX and PDF Utilities
        if: steps.check_inprogress_file.outputs.inprogress_file_exists == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-xetex texlive-bibtex-extra biber texlive-extra-utils

      - name: Create Output Directory
        if: steps.check_inprogress_file.outputs.inprogress_file_exists == 'true' || github.event_name == 'workflow_dispatch'
        run: mkdir -p output

      - name: Compile LaTeX Files
        if: steps.check_inprogress_file.outputs.inprogress_file_exists == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          for file in input/*.txt; do
            base_name=$(basename "$file" .txt)
            lualatex -interaction=nonstopmode -output-directory=output "$file"
            if [ -f "output/$base_name.bcf" ]; then
              biber output/"$base_name"
            fi
            lualatex -interaction=nonstopmode -output-directory=output "$file"
            lualatex -interaction=nonstopmode -output-directory=output "$file"
          done

      - name: Delete Temporary LaTeX Files
        if: steps.check_inprogress_file.outputs.inprogress_file_exists == 'true' || github.event_name == 'workflow_dispatch'
        run: rm -f output/*.{aux,log,lof,lot,toc,bbl,blg,out,synctex.gz,fdb_latexmk,fls,bcf,run.xml}

      - name: Auto Commit PDFs
        if: steps.check_inprogress_file.outputs.inprogress_file_exists == 'true' || github.event_name == 'workflow_dispatch'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Compiled LaTeX files"
          push_options: '--force'
          file_pattern: 'output/*.pdf'

      - name: Upload PDFs
        if: steps.check_inprogress_file.outputs.inprogress_file_exists == 'true' || github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pamphlets
          path: output/*.pdf
