name: Generate Booklet PDFs

on:
  workflow_run:
    workflows: ["Compile LaTeX Files"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write  # Grant write access for committing and pushing

jobs:
  generate-booklets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

   #   - name: Download Compiled PDFs
   #     uses: actions/download-artifact@v4
   #     with:
   #      name: compiled-pamphlets
   #       path: output/

      - name: Install PDF Processing Tools
        run: |
          sudo apt update
          sudo apt install -y texlive-extra-utils
      - name: Process PDF Files
        run: |
          for file in output/*\ -\ View.pdf; do
            if [[ -f "$file" ]]; then
              echo "Processing booklet for: $file"
              base_name="${file% - View.pdf}"
              pdfbook2 "$file"
              mv "${file%.*}-book.pdf" "${base_name} - Print.pdf"
              echo "Created ${base_name} - Print.pdf"
            else
              echo "Warning: File not found for booklet processing: $file"
            fi
          done
      - name: Auto Commit PDFs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Compiled LaTeX files with View and Print versions"
          push_options: '--force'
          file_pattern: 'output/*.pdf'

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: compiled-and-booklet-pdfs
          path: output/*.pdf

      # --- NEW STEP: Delete the inprogress file ---
      - name: Delete inprogress file
        run: |
          if [ -f "input/inprogress.inprogress" ]; then
            echo "Deleting input/inprogress.inprogress..."
            rm "input/inprogress.inprogress"
            echo "input/inprogress.inprogress deleted."
          else
            echo "input/inprogress.inprogress not found, skipping deletion."
          fi
        # This action uses git-auto-commit-action to commit the deletion,
        # otherwise the file will be deleted on the runner but not in the repo.
        # Ensure you want to commit this deletion back to the repository.
      - name: Commit inprogress file deletion
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Cleaned up inprogress file"
          # Only commit if changes exist (i.e., if the file was deleted)
          commit_options: '--no-verify --allow-empty'
          file_pattern: 'input/inprogress.inprogress'
          # If you don't want to push immediately, remove push_options or set it to ''
          push_options: '--force'
